language: node_js

node_js:
  - "7"

sudo: false

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
install:
  - yarn global add codecov

script:
  - yarn run test:coverage
  - codecov
